*** empty log message ***

diff --git a/branches/new_threads/qedo/configure b/branches/new_threads/qedo/configure
--- a/branches/new_threads/qedo/configure
+++ b/branches/new_threads/qedo/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS XERCESDIR CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT SET_MAKE RANLIB ac_ct_RANLIB LN_S INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA HAVE_MICO_CONFIG HAVE_MKDIR_PROG CC CFLAGS ac_ct_CC HAVE_XERCES XERCES_LIBS XERCES_INCLUDE CPP EGREP LIBOBJS OS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS XERCESDIR MICODIR CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT SET_MAKE RANLIB ac_ct_RANLIB LN_S INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA HAVE_MICO_CONFIG HAVE_MKDIR_PROG CC CFLAGS ac_ct_CC HAVE_XERCES XERCES_LIBS XERCES_INCLUDE CPP EGREP LIBOBJS OS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -858,6 +858,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-xerces-c=xercesdir         use Xerces installed in xercesdir
+  --with-mico=micodir         use Mico installed in xercesdir
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -1299,6 +1300,16 @@ if test "${with_xerces+set}" = set; then
   XERCESDIR=$withval
 else
   XERCESDIR=""
+fi;
+
+
+
+# Check whether --with-mico or --without-mico was given.
+if test "${with_mico+set}" = set; then
+  withval="$with_mico"
+  MICODIR=$withval
+else
+  MICODIR=""
 fi;
 
 
@@ -2063,6 +2074,49 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
+
+MICODIR=""
+if test X"$with_mico" != X ;then
+	MICODIR="$with_mico"
+# Extract the first word of "mico-config", so it can be a program name with args.
+set dummy mico-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_HAVE_MICO_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$HAVE_MICO_CONFIG"; then
+  ac_cv_prog_HAVE_MICO_CONFIG="$HAVE_MICO_CONFIG" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $MICODIR/bin
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_HAVE_MICO_CONFIG="yes"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_prog_HAVE_MICO_CONFIG" && ac_cv_prog_HAVE_MICO_CONFIG="no"
+fi
+fi
+HAVE_MICO_CONFIG=$ac_cv_prog_HAVE_MICO_CONFIG
+if test -n "$HAVE_MICO_CONFIG"; then
+  echo "$as_me:$LINENO: result: $HAVE_MICO_CONFIG" >&5
+echo "${ECHO_T}$HAVE_MICO_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+   { echo "$as_me:$LINENO: please make sure, that $MICODIR/bin/idl will run" >&5
+echo "$as_me: please make sure, that $MICODIR/bin/idl will run" >&6;}
+else
 # Extract the first word of "mico-config", so it can be a program name with args.
 set dummy mico-config; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -2099,6 +2153,15 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+fi
+if test "$HAVE_MICO_CONFIG" != "yes"; then
+  { { echo "$as_me:$LINENO: error: support until now only Mico, found no mico-config" >&5
+echo "$as_me: error: support until now only Mico, found no mico-config" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+
 # Extract the first word of "mkdir", so it can be a program name with args.
 set dummy mkdir; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -2134,7 +2197,6 @@ else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
-
 
 
 # Checks for libraries.
@@ -6173,6 +6235,7 @@ s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
 s,@XERCESDIR@,$XERCESDIR,;t t
+s,@MICODIR@,$MICODIR,;t t
 s,@CXX@,$CXX,;t t
 s,@CXXFLAGS@,$CXXFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
